# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /mnt/Games/Linux_Unreal_Engine_5.6.1

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	MovementProject-Android-DebugGame  \
	MovementProject-Android-Development  \
	MovementProject-Android-Shipping  \
	MovementProject-Linux-DebugGame  \
	MovementProject-Linux-Development  \
	MovementProject-Linux-Shipping  \
	MovementProject-LinuxArm64-DebugGame  \
	MovementProject-LinuxArm64-Development  \
	MovementProject-LinuxArm64-Shipping  \
	MovementProject \
	MovementProjectEditor-Linux-DebugGame  \
	MovementProjectEditor-Linux-Development  \
	MovementProjectEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend MovementProjectEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug MovementProjectEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

MovementProject-Android-DebugGame:
	 $(BUILD) MovementProject Android DebugGame  -Project="/mnt/Games/UnrealProjects/WerewolfProject/MovementProject.uproject" $(ARGS)

MovementProject-Android-Development:
	 $(BUILD) MovementProject Android Development  -Project="/mnt/Games/UnrealProjects/WerewolfProject/MovementProject.uproject" $(ARGS)

MovementProject-Android-Shipping:
	 $(BUILD) MovementProject Android Shipping  -Project="/mnt/Games/UnrealProjects/WerewolfProject/MovementProject.uproject" $(ARGS)

MovementProject-Linux-DebugGame:
	 $(BUILD) MovementProject Linux DebugGame  -Project="/mnt/Games/UnrealProjects/WerewolfProject/MovementProject.uproject" $(ARGS)

MovementProject-Linux-Development:
	 $(BUILD) MovementProject Linux Development  -Project="/mnt/Games/UnrealProjects/WerewolfProject/MovementProject.uproject" $(ARGS)

MovementProject-Linux-Shipping:
	 $(BUILD) MovementProject Linux Shipping  -Project="/mnt/Games/UnrealProjects/WerewolfProject/MovementProject.uproject" $(ARGS)

MovementProject-LinuxArm64-DebugGame:
	 $(BUILD) MovementProject LinuxArm64 DebugGame  -Project="/mnt/Games/UnrealProjects/WerewolfProject/MovementProject.uproject" $(ARGS)

MovementProject-LinuxArm64-Development:
	 $(BUILD) MovementProject LinuxArm64 Development  -Project="/mnt/Games/UnrealProjects/WerewolfProject/MovementProject.uproject" $(ARGS)

MovementProject-LinuxArm64-Shipping:
	 $(BUILD) MovementProject LinuxArm64 Shipping  -Project="/mnt/Games/UnrealProjects/WerewolfProject/MovementProject.uproject" $(ARGS)

MovementProject: MovementProject-Linux-Development

MovementProjectEditor-Linux-DebugGame:
	 $(BUILD) MovementProjectEditor Linux DebugGame  -Project="/mnt/Games/UnrealProjects/WerewolfProject/MovementProject.uproject" $(ARGS)

MovementProjectEditor-Linux-Development:
	 $(BUILD) MovementProjectEditor Linux Development  -Project="/mnt/Games/UnrealProjects/WerewolfProject/MovementProject.uproject" $(ARGS)

MovementProjectEditor: MovementProjectEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/mnt/Games/UnrealProjects/WerewolfProject/MovementProject.uproject" -Game 

.PHONY: $(TARGETS)
